### ISSUE TITLE
Does this work with guile?

### ISSUE THREAD

**Issue by UnkindPartition** [the-little-prover/j-bob#4]
With guile, I get

```
% guile
GNU Guile 2.0.11
Copyright (C) 1995-2014 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> (load "j-bob-lang.scm")
scheme@(guile-user)> (load "j-bob.scm")
scheme@(guile-user)> (load "little-prover.scm")
scheme@(guile-user)> (chapter1.example1)
$1 = (car (cons (quote ham) (quote (eggs))))
```

I thought the result was supposed to be `'ham`.

**Comment by carl-eastlund** [comment]
The first thing I've found, looking up Guile / R5RS compatibility, is that Guile is case-sensitive, while R5RS is case-insensitive.  I suspect that somewhere in our code we have alternated between uppercase and lowercase letters for paths (Q, A, and E).  I'll try to fix up the code to be consistent about case, and I'll see if that helps.

Thanks for the report!

**Comment by carl-eastlund** [comment]
I've just pushed a fix for this.  The problem was the definition of natp, which referred to < instead of s.< from above.
